# NumPy 

NumPy (stands for Numerical Python) is a general packages used for processing arrays. It provides a high performance, multidimensional array object and tools to work with these arrays and is popular for scientific computing in Python.

Importing NumPy library for use in our Python code.

In [2]:
import numpy as np

## NumPy Dimensions

In [4]:
# Example of 0-D Array
dim0_arr = np.array(42)
print('Dimension of dim0_arr:',dim0_arr.ndim)

#Example of 1-D Array
dim1_arr = np.array([1, 2, 3, 4, 5])
print('Dimension of dim1_arr:',dim1_arr.ndim)

#Example of 2-D Array
dim2_arr = np.array([
		 [1, 2, 3],
		 [4, 5, 6]
])
print('Dimension of dim2_arr:',dim2_arr.ndim)

#Example of 3-D Array 2 by 2 by 3
dim3_arr = np.array([
		[[1, 2, 3], [4, 5, 6]], 
		[[1, 2, 3], [4, 5, 6]]
])
print('Dimension of dim3_arr:',dim3_arr.ndim)
#Example of creating a 5-D Array
dim5_arr = np.array([1, 2, 3, 4], ndmin=5)
print('Dimension of dim5_arr:',dim5_arr.ndim)

print('dim5_arr:',dim5_arr) # [[[[[1 2 3 4]]]]]



Dimension of dim0_arr: 0
Dimension of dim1_arr: 1
Dimension of dim2_arr: 2
Dimension of dim3_arr: 3
Dimension of dim5_arr: 5
dim5_arr: [[[[[1 2 3 4]]]]]


## Creating NumPy Array

In [5]:
# creating a python list
x = [1, 2, 3]

# transforming into NumPy array
x = np.array(x)    
print(x)         

[1 2 3]


In [6]:
# creating a NumPy array
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# prints <class 'numpy.ndarray'>
print(type(x))


<class 'numpy.ndarray'>


### Creating array with all zeros

In [30]:
x = np.zeros((2, 2))
print(x)

[[0. 0.]
 [0. 0.]]


### Create 2x2 array with a certain value

In [31]:

z = np.full((2, 2), 7) # Return a 2x2 array filled with the value 7
print(z)

zero = np.full((2, 2), 0) # Return a 2x2 array filled with the value 7
print(zero)

# create an array of float data type
float_arr = np.array([1, 2, 3, 4], dtype='f')
print(float_arr)

[[7 7]
 [7 7]]
[[0 0]
 [0 0]]
[1. 2. 3. 4.]


## Creating NumPy Array from Tuple

In [32]:
import numpy as np

# creating a python tuple
x = (1, 2, 3)

# transforming into numpy array
y = np.array(x)    

print(y)# [1 2 3]

[1 2 3]


# Shapes

## 2 Dimensional Shapes

In [7]:
dim2_arr = np.array([
		 [1, 2, 3],
		 [4, 5, 6]
]) 
print(dim2_arr.shape)# (2,3)
#dim0_arr = np.array(42)
print(dim0_arr.shape)

(2, 3)
()


## 3 dimensional shapes

In [8]:
dim3_arr = np.array([
		[[1, 2, 3], [4, 5, 6]], 
		[[1, 2, 3], [4, 5, 6]]
])
print(dim3_arr.shape) # (2,2,3)


(2, 2, 3)


# Reshaping

In [9]:
# arr is an ONE- dimensional ‘numpy’ array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#Reshape
newarr = arr.reshape(4, 3)
print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#Reshape from 1 D to 3 D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print('Newarr shapes: ',newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Newarr shapes:  (2, 3, 2)


# Iteration

In [11]:
# Iterate through an ONE- dimensional ‘numpy’ array
arr = np.array([1, 2, 3, 4, 5, 6])
for x in arr:
  print(x)

# Iterate through a TWO - dimensional NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr:
  print(row)
  
#Printing the individual value in the matrix
for row in arr:
  for ele in row:
    print(ele)


1
2
3
4
5
6
[1 2 3]
[4 5 6]
1
2
3
4
5
6


## Indexing

In [12]:
# Get the first element from the array
arr = np.array([1, 2, 3, 4])
print(arr[0]) # 1
# The sum of third and fourth element from the array
arr = np.array([1, 2, 3, 4])
print(arr[2]+arr[3]) # 7

1
7


## Boolean Indexing

In [13]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

# set criteria for even-numbers
bool_mat = (mat % 2 == 0)
print(bool_mat)
print(mat[bool_mat])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


# Slicing

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slicing elements from 2nd  (index 1) to 5th (index 4) from the following array
print(arr[1:5]) # [2 3 4 5]

# Slicing elements from 5th element to the end of the array
print(arr[4:]) # [5 6 7]

# Slicing elements from the beginning to 5th element (index 4 and not included)
print(arr[:4]) # [1 2 3 4]

#Slicing elements from beginning with step=2
print(arr[::2]) # [1 3 5 7]

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[1 3 5 7]


## Slicing multi-dimensions

In [18]:
# creates a numpy array
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# extracts data
print(mat[0:2,1:2]) 
#print(mat[:,-1])
'''
mat[:-1] will extract the all rows and -1 is the last column thus the output is only the last column
mat[:-1:-1] will extract the last column values of the above partial array which is [3,6]
'''
#print(mat[1:,1:])

[[2]
 [5]]


'\nmat[:-1] will extract the all rows and -1 is the last column thus the output is only the last column\nmat[:-1:-1] will extract the last column values of the above partial array which is [3,6]\n'

# Element-Wise Scalar Operations

In [19]:
# creating a numpy array
a = np.array([
    [1, 0],
    [1, 2]
])

# add 2 to each element
a_plus2 = a + 2

# prints [[3,2],[3,4]]
print(a_plus2)

# multiple 2 to each element
a_times2 = a * 2

# prints[[2,0],[2,4]]
print(a_times2)

[[3 2]
 [3 4]]
[[2 0]
 [2 4]]


# Element-Wise Matrix Operations

In [20]:
# creating a numpy array
a = np.array([
    [1, 0],
    [1, 2]
])

# creating a second numpy array
b = np.array([
    [0, 2],
    [1, 1]
])

# element-wise addition
ab_plus = a + b

# prints [[1,2],[2,3]]
print(ab_plus)

# element-wise multiplication
ab_mul = a * b

# prints [[0,0],[1,2]]
print(ab_mul)

[[1 2]
 [2 3]]
[[0 0]
 [1 2]]


# Dot Product

In [21]:
# create a 1x2 matrix
# 1D - 1 row by 2 cols
a = np.array([1, 2])

# create a 2x1 matrix
# 2D - 2 rows by 1 col
b = np.array([[3],[4]])

# prints dimension of matrix
print(b.ndim)   # prints 2

# prints shape of matrix
print(b.shape)  # prints (2, 1)

# performs matrix-multiplication
a_mul_b = np.dot(a, b)

# prints [11]
print(a_mul_b)

# a_mul_b is a 1D matrix
print(a_mul_b.ndim)     # prints 1

# a_mul_b has a single column
print(a_mul_b.shape)    # prints (1,)

2
(2, 1)
[11]
1
(1,)


# Stacking Matrices

In [23]:
# creating individual matrices
mat1 = np.array([1, 2, 3])
mat2 = np.array([4, 5, 6])
mat3 = np.array([7, 8, 9])

# concat along axis=0 (row-direction)
mat_axis0 = np.concatenate(([mat1], [mat2], [mat3]), axis=0)

# prints [[1,2,3],[4,5,6],[7,8,9]]
print(mat_axis0) 

# concat along axis=1 (column-direction)
mat_axis1 = np.concatenate(([mat1], [mat2], [mat3]), axis=1)

# prints [[1,2,3,4,5,6,7,8,9]]
print(mat_axis1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


# Splitting

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) # [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


# Searching

In [29]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

#print(x)

#print(x[0])

search_arr = arr[x[0]]
#print(search_arr)

# Filter away all the 4s in the array
y = np.where(arr != 4)
filter_arr = arr[y[0]]
print(filter_arr) 

[1 2 3 5]


## Sorting

In [48]:
#Sort the array
#Sort the array
print(np.sort(arr)) # [1 2 3 4 4 4 5]

#Reverse sorting
print(np.sort(arr)[::-1])#making use of array slicing



[1 2 3 4 5 6]
[6 5 4 3 2 1]


# Random

In [30]:
from numpy import random

# Generate a random integer from 0 to 100
x = random.randint(100)
print(x)
# Generate a 1-D array containing 5 random integers from 0 to 100
x=random.randint(100, size=(5))
print(x)
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
x = random.randint(100, size=(3, 5))
print(x)
# Generate a random float
x = random.rand()
print(x)
# Generate an array containing 5 random float
x = random.rand(5)
print(x)
# Generate a random integer from an array of possible integers [3,5,7,9]
x = random.choice([3, 5, 7, 9])
print(x)
# Generate a random integer array of 4 elements from an array of possible integers [3,5,7,9]
x = random.choice([3, 5, 7, 9],size=(4))
print(x)
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)
x = random.choice([3, 5, 7, 9],size=(3,5))
print(x)

60
[39 93 92  1 62]
[[90 94 62 22 22]
 [94 73 66 74 13]
 [43 82  9 12 53]]
0.7164674086617129
[0.56039296 0.4535317  0.72072503 0.0150898  0.56066079]
9
[5 7 7 5]
[[9 9 9 3 3]
 [7 9 9 3 9]
 [9 9 9 3 9]]


# Others 

In [51]:
import numpy as np
# Culmulative sum
arr = np.array([3,4,5])
print(np.cumsum(arr))
print(np.cumsum(arr)[-1])

# Define the arrays
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# Perform element-wise subtraction
result = np.subtract(arr1, arr2)

print(result)

[ 3  7 12]
12
[ 9 18 27 36]
